name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Go 1.16.7
        uses: actions/setup-go@v1.1.2
        with:
          go-version: '1.16.7'
      - name: Go test
        run: go test ./app -v